### PR TITLE
For review

### LINKED ISSUE #16: Setup database

### LINKED ISSUE #68: Work on the Pet Store Page

### PR DESCRIPTION
**Pull request by seeddhee**
1) Worked on the front end of the Virtual Shop Page
2)Worked on styling the Shop with CSS
3)Added different components like the pet and the accessories
4)Added the logo

Screenshot (17)

### CODE REVIEW

**Review by mhayes2772 — COMMENTED** [review]
You have a different component for each image, but you could have one "MyImage" component that you pass src, alt and classname to signifigantly reduce the amount of files/code.

**Comment by lemezze** [comment]
I'd like to have more padding in the items boxes so that they can be centered and not look too crowded. I'd also change the alt tag to be more descriptive of the "coming soon" box. You also forgot to include the points amount at the top right and the shadow under the pet/logo. Other than that and the comment someone else made, I think this looks good!

**Comment by tamimfatahi** [comment]
I think with Michael's recent changes, it'd be nice to add in the background portrait in the future to negate some of the blank space. Other than that, it looks great! I'm a fan of the organization of the files in their own separate components.

**Comment by dreassantos** [comment]
Using the asset images separately from the button's image may have been a better choice. If we use it this way, we will have to make the entire image a button, and clicking the purchase button wouldn't matter. A flexbox would be great for this because each container could have an image, a text element, and a button with the cost. They could be used as a shop item component. Then you can send the image path and the cost to the component, and it would be the same for each shop item. Other than the image comments that our team stated, everything looks good.

**Pull request merged**
